#  조건문

## if 조건문

In [2]:
a = 100
b = 200

if a > b :   #자동으로 들려쓰기가 됨 
    print("안녕하세요")
else :       #첫번째 조건을 만족하지 않았을 때 
    print ("Hi")

Hi


In [7]:
c = int(input("첫번째 정수를 입력해 주세요 : "))
d = int(input("두번째 정수를 입력해 주세요 : "))

if c > d :
    print(c,"정수가",d,"정수보다 큽니다.")
elif c == d :
    print(c,"정수가",d,"정수와 같습니다.")
else :
    print(d,"정수가",c,"정수보다 큽니다.")

첫번째 정수를 입력해 주세요 : 2000
두번째 정수를 입력해 주세요 : 2000
2000 정수가 2000 정수와 같습니다.


In [10]:
#값을 입력받아서 양수인지 음수 인지 판단
num = int(input('정수를 입력해주세요 : '))
if num > 0 :
    print("입력한 수는 양수입니다.")
elif num == 0 : 
    print("입력한 수는 0 입니다.")
else :
    print("입력한 수는 음수입니다.")

수를 입력해주세요 : -100
음수입니다.


In [11]:
#값을 입력받아서 양수인지 음수 인지 판단
'''
num = int(input('정수를 입력해주세요 : '))
if num > 0 :
    pass  #if문 전체를 건너뜀
elif num == 0 : 
    print("입력한 수는 0 입니다.")
else :
    print("입력한 수는 음수입니다.")
'''

'\nnum = int(input(\'정수를 입력해주세요 : \'))\nif num > 0 :\n    pass  #if문 전체를 건너뜀\nelif num == 0 : \n    print("입력한 수는 0 입니다.")\nelse :\n    print("입력한 수는 음수입니다.")\n'

In [3]:
score  = int(input('성적을 입력해주세요 : '))

if score >= 95 :
    print("학생의 성적은 A+ 입니다.")
elif score >= 90 :    
    print("학생의 성적은 A 입니다.")
elif score >= 80: 
    print("학생의 성적은 B+ 입니다.")
elif score >= 75 : 
    print("학생의 성적은 C 입니다.")
else : 
    print("학생의 성적은 F 입니다.")

성적을 입력해주세요 : 100
학생의 성적은 A+ 입니다.


In [1]:
A, B = 100, 20

if A > B:
    pass
else : 
    print('Error')

# 반복문

* For 문   (더 많이 사용 됨)
* While 문

In [1]:
i = 0

while i<5:
    print("Hi Python~!")
    i = i + 1 

print('반복종료')

Hi Python~!
Hi Python~!
Hi Python~!
Hi Python~!
Hi Python~!
반복종료


In [4]:
i = 1

while i < 5:
    print("Hi")
    break # 싹다 무시하고 멈춤 이런식으로도 종료가 가능 (자주 사용x)
    i = i + 1    # '='는 같다가 아니고 대입해준다는 의미
print("반복종료")

Hi
반복종료


In [21]:
list1 = [1,2,3,4,5,6]
for i in list1 : # range라는 범위 n부터 m직전까지 반복을 시켜줘라
    print(i+10)

11
12
13
14
15
16


In [22]:
score = [100, 20, 55, 70, 30]

for i in score :
    
    if i > 60 :
        print("합격")
    else :
        print("불합격")


합격
불합격
불합격
합격
불합격


* 1부터 100까지 더하는 프로그램

In [34]:
n = 10000         #1000000000000000이면 결과값 가져오는 시간이 아주 김
sum = 0   # for문 밖에서 써야됨 

for i in range(1,n+1) :     #가우스공식 이용하면 for문 안써도됨 / 수열을 알면 편함
    sum = sum + i
print(sum)

50005000


In [31]:
n = 10000000                  #결과가 아주 빨리 나옴   <-- 프로그래밍할때 반복수가 적고 빨리 결과를 낼 수있는것을 복잡도 라고함 
sum = n*(n+1)/2               # 단순하고 빠르게 처리하게 끔 할 수 있는 것이 좋음  / 짧고 간결하고 빠르게 결과를 낼 수 있어야 함
print(sum)                    #복잡도를 최대한 줄이는 게 좋음

50000005000000.0


* 연습문제 2-2
*(값을 입력 받아 홀수인지 짝수인지 판별하는 프로그램 만들기)


In [39]:
num = int(input('값을 입력해주세요 : '))
nums = num%2
if nums == 1 :
    print('홀수입니다.')
else :
    print('짝수입니다.')

값을 입력해주세요 : 21
홀수입니다.


* 연습문제 2-3 (키와 몸무게를 입력받아, 비만도(BMI)를 판별하는 프로그램 만들기)

In [49]:
weight = int(input('몸무게를 입력해주세요 : '))
height = int(input('키를 입력해주세요 : '))
bmi = weight/(height/100)**2

print(bmi)
if bmi < 18.5 : 
    print("저체중 입니다.")
elif 18.5 < bmi < 22.9 :
    print("정상 체중입니다.")
elif 23 < bmi <24.9 : 
    print("과체중 입니다.")
elif 25< bmi < 29.9 : 
    print("경도비만 입니다.")
else: 
    print("고도비만 입니다.")

몸무게를 입력해주세요 : 63
키를 입력해주세요 : 173
21.04981790236894
정상 체중입니다.


 * 연습문제 2-4 (A 부서의 월 매출이 아래와 같을 때, For문을 이용하여, A부서의 평균 월 매출 계산 (리스트와 For문을 이용해서 계산)


In [56]:
list1 = [5500, 5300, 6700, 5500, 5800]
avg = 0

for list in list1 : 
    avg = avg +list
print(avg)

28800


* 연습문제 2-5 (For반복문을 중첩하여, 아래와 같이 *기호를 피라미드로 출력하는 프로그램 제작)

In [54]:
p

*
**
***
****
*****


* 정수를 입력받아 해당 수의 구구단을 출력하는 프로그램 만들기

In [58]:
num = int(input("정수를 입력하시오 : "))

for i in range(1,10):
    result = num * i
    print(num, "X", i, '=', result)

정수를 입력하시오 : 120
120 X 1 = 120
120 X 2 = 240
120 X 3 = 360
120 X 4 = 480
120 X 5 = 600
120 X 6 = 720
120 X 7 = 840
120 X 8 = 960
120 X 9 = 1080


* 연습문제 2-7 (for문과 if문을 이용하여, 정수를 입력 받아 정수의 약수를 구하는 프로그램 제작)

* 연습문제 2-8

# 함수

* x --f--> y  

In [39]:
def sum_1(data):  #sum_1 이 함수이름 / data가 변수 (x)
    sum = data*(data+1)/2
    return sum    #return 뒤가 y

print(sum_1(2))    #함수에 맞는 이름이 나왔을 때 함수가 진행이 되고 코드가 진행이 됨
                     #대부분 앞에 함수들을 여러개 만들어 놓고 진행함

3.0


In [67]:
def circle_area(row):
    return row**2*3.14

In [68]:
circle_area(100)

31400.0

* 연습문제1-2 (20190603으로 입력됐을 때 함수를 이용하여 0000-00-00 형태로 바꿔보기)

In [5]:
def trans_date(data):
    data = str(data)
    result = data[0:4]+"-"+data[4:6]+"-"+data[6:]
    return result

In [6]:
data = int(input('날짜를 입력하십시오 : '))
trans_date(data)

날짜를 입력하십시오 : 20190603


'2019-06-03'

* 연습문제 2-9 (입력하는 모든 수의 평균을 계산하는 함수 만들기)

In [45]:
def avg_fun(*data):
    for i in data:
        avg = (i*(i+1))/2
    return avg/len(data)

In [46]:
avg_fun(1,2,3,4,5,6,6)

3.0

# Library

* numpy(다차원 배열 연산 처리에 특화되어 있는 라이브러리, matrix,행렬처리 할 때 많이 사용) & pandas(excel의 정형 data들을 다루는 package, 엑셀이랑 똑같다고 생각하면됨 엑셀을 파이썬버전으로 바꿔놓은 거임, 속도가 굉장히 빠름, 매우중요 !! )  <-- 가장 중요함 
* 데이터 불러오기 및 전처리 
* Matplot (python에서 나올 수 있는 데이터로 그래프를 그릴 수 있는 라이브러리) & Seabom(시각화 할 때 사용)
* Sklearn (회귀분석, 머신러닝을 할 때 이용하는 라이브러리)
* Tensorflow & Kerase (딥러닝 할 때)

# Numpy

In [48]:
import numpy as np #numpy라는 library를 가져와서 사용하겠다는 의미 #약어 np라고 줄여서 사용하겠다

In [49]:
data = [6,7,8,9,10,11]
data.mean()  #np가 아니라서 결과가 안나옴

AttributeError: 'list' object has no attribute 'mean'

In [52]:
data2 = np.array([6,7,9,9,10,11])
data2.mean()

8.666666666666666

In [54]:
print(type(data))
print(type(data2)) #데이터의 구조를 알려주는것  #numpy라는 라이브러리 안에있는 ndarray라는 방법을 이용한것

<class 'list'>
<class 'numpy.ndarray'>


In [55]:
data2.dtype #리스트안에 있는 데이터의 타입을 알려주는 것 

dtype('int32')

In [56]:
data3 = np.array([1,2,3,4,5.55])
data3.dtype    #float : 실수형이다.

dtype('float64')

In [58]:
data4 = np.array([1,2,3,4,5.55,"가"])
data4.dtype    #U32 : 문자형이 들어가있다 

dtype('<U32')

In [59]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

** Matrix Operation

In [60]:
matrix1 = np.array([[1,2],
                    [3,4],
                    [5,6]])
matrix2 = np.array([[10,10],[30,30],[50,60]])

print(matrix1 + matrix2)   #matrix끼리 연산이 가능하다

[[11 12]
 [33 34]
 [55 66]]


In [61]:
matrix1**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [62]:
matrix1.sum()

21

In [63]:
matrix1.mean()   #평균구하기

3.5

In [66]:
matrix1.std()    # std : 표준편차

1.707825127659933

In [67]:
matrix1.shape    # 3 by 2 행렬이다. 

(3, 2)

In [68]:
np.random.randn(10)  #평균이 0이고 표준편차가 1(?) 인 random하게 10개를 생성해라

array([-0.68034901, -0.87654141, -2.52552552,  0.09726759, -0.78361029,
        0.11048322, -0.89389196,  1.57924545,  1.61280321, -0.96319833])

In [69]:
np.random.randn(3,3)   #3 by 3 행렬 형태로 생성해라 (비정형 데이터를 처리할 때 많이 사용)

array([[ 0.15903101,  0.74418311, -0.12987518],
       [-0.6680434 , -1.31465378,  0.83851064],
       [-1.34293681,  0.19712982, -1.63994737]])

** 값을 찾는 또는 바꾸는 함수 **

In [83]:
arr = np.array([1,2,3,4,5,6,7])

In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
arr[0]  #맨 앞에 있는 데이터를 가져옴

1

In [86]:
arr[-1] #맨뒤에 있는 데이터를 가져옴

7

In [87]:
arr[:3]  #2번째 데이터까지 가져옴

array([1, 2, 3])

In [88]:
arr[3:]  #3번째 데이터 다음을 다 가져옴

array([4, 5, 6, 7])

In [89]:
arr[:]   #데이터를 싹 다 가져옴

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
arr[0]  #0번째 데이터를 바꾸고 싶을 때 

1

In [91]:
arr[0] = 100

In [92]:
arr

array([100,   2,   3,   4,   5,   6,   7])

# Pandas

In [7]:
import pandas as pd
import numpy as np   # 관례적으로 pandas쓸 때는 numpy랑 같이 씀

** Pandas 데이터 구조 **
* 1. Series 수열 (key-value , index-value(값들의 순서가 매겨져있음))
* 2. Dataframe 2차원 구조 (실무에서 가장많이 쓰일 , 엑셀형태 (index(순서), column(주제들) , value(값들) 형태로 이루어져 있음)

## Series

In [98]:
s1 = pd.Series([1,2,3,4,5,6,7]) #S가 대문자임 !!!! 
s1       #앞이 데이터 순서 알려주는 index #뒤에 데이터 값

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [99]:
s1.mean()

4.0

In [100]:
s1.sum()

28

In [101]:
s1.std()   #표준편차

2.160246899469287

In [102]:
s1.max()   #최대값

7

In [103]:
s1.min()   #최소값

1

In [106]:
pd.Series(['홍길동','성춘향','이몽룡','임꺽정'],index=['하나','두시기','석삼','너구리'],name = '출석부')

하나     홍길동
두시기    성춘향
석삼     이몽룡
너구리    임꺽정
Name: 출석부, dtype: object

In [116]:
dic1 = {"name":"Sam","age":22,"gender":"male","job":"student"}     #Dictionary로 해도 됨
s1 = pd.Series(dic1,name= 'O1')

In [117]:
s1['name']

'Sam'

In [118]:
s1

name          Sam
age            22
gender       male
job       student
Name: O1, dtype: object

In [119]:
s1[s1=='male']   #male이 들어있는 항목을 가져와라 

gender    male
Name: O1, dtype: object

## DataFrame
* index(인덱스)
* Column(변수)
* Value(값)

In [8]:
table1 = [
    ['2019-01-01',1000,'False','gum'],
    ['2019-01-04',3000,'True','snack'],
    ['2019-01-06',2000,'True','beverage'],
    ['2019-01-06',1000,'True','gum']
          ]

pd.DataFrame(table1)

0     1      2         3
0  2019-01-01  1000  False       gum
1  2019-01-04  3000   True     snack
2  2019-01-06  2000   True  beverage
3  2019-01-06  1000   True       gum

In [11]:
pd.DataFrame(table1, columns=['일자','가격','구매여부','제품'])

일자    가격   구매여부        제품
0  2019-01-01  1000  False       gum
1  2019-01-04  3000   True     snack
2  2019-01-06  2000   True  beverage
3  2019-01-06  1000   True       gum

In [77]:
table2 = {
    '일자':['2019-01-01','2019-01-04','2019-01-06','2019-01-06'],
    '가격':[1000,3000,2000,1000],
    '구매여부':['False','True','True','True'],
    '제품': ['gum','snack','beverage','gum'],
}
pd.DataFrame(table2)

일자    가격   구매여부        제품
0  2019-01-01  1000  False       gum
1  2019-01-04  3000   True     snack
2  2019-01-06  2000   True  beverage
3  2019-01-06  1000   True       gum

In [78]:
name = ['A','B','C','D']

df1 = pd.DataFrame(table2,index=name)
df1

일자    가격   구매여부        제품
A  2019-01-01  1000  False       gum
B  2019-01-04  3000   True     snack
C  2019-01-06  2000   True  beverage
D  2019-01-06  1000   True       gum

In [19]:
df1.head()

일자    가격   구매여부        제품
A  2019-01-01  1000  False       gum
B  2019-01-04  3000   True     snack
C  2019-01-06  2000   True  beverage
D  2019-01-06  1000   True       gum

In [16]:
df1.columns

Index(['일자', '가격', '구매여부', '제품'], dtype='object')

In [17]:
df1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
df1.values

array([['2019-01-01', 1000, 'False', 'gum'],
       ['2019-01-04', 3000, 'True', 'snack'],
       ['2019-01-06', 2000, 'True', 'beverage'],
       ['2019-01-06', 1000, 'True', 'gum']], dtype=object)

In [21]:
df1.tail(2)

일자    가격  구매여부        제품
C  2019-01-06  2000  True  beverage
D  2019-01-06  1000  True       gum

In [22]:
df1['제품']

A         gum
B       snack
C    beverage
D         gum
Name: 제품, dtype: object

In [23]:
df1['가격'].head()

A    1000
B    3000
C    2000
D    1000
Name: 가격, dtype: int64

### Sorting

In [24]:
df1.sort_index()    #데이터를 Index기준 순서로 정렬하고 싶을 때

일자    가격   구매여부        제품
A  2019-01-01  1000  False       gum
B  2019-01-04  3000   True     snack
C  2019-01-06  2000   True  beverage
D  2019-01-06  1000   True       gum

In [25]:
df1.sort_index(ascending  = False)       # ascending --> 오름차순 / 내림차순 정렬 할 수 있다.

일자    가격   구매여부        제품
D  2019-01-06  1000   True       gum
C  2019-01-06  2000   True  beverage
B  2019-01-04  3000   True     snack
A  2019-01-01  1000  False       gum

In [26]:
df1.sort_values(by='일자')   #데이터를 특정 Column을 기준으로 정렬할 때

일자    가격   구매여부        제품
A  2019-01-01  1000  False       gum
B  2019-01-04  3000   True     snack
C  2019-01-06  2000   True  beverage
D  2019-01-06  1000   True       gum

In [27]:
df1.sort_values(by=['일자','가격'])    #리스트를 이용해 두 column을 기준으로 정렬

일자    가격   구매여부        제품
A  2019-01-01  1000  False       gum
B  2019-01-04  3000   True     snack
D  2019-01-06  1000   True       gum
C  2019-01-06  2000   True  beverage

### Operation

* 연속형 데이터에 대한 기본 통계 연산

In [28]:
df1['가격'].mean()

1750.0

In [29]:
df1['가격'].sum()

7000

In [30]:
df1['가격'].min()

1000

In [31]:
df1['가격'].max()

3000

In [32]:
df1['가격'].std() #표준편차

957.427107756338

* 범주형 데이터에 대한 연산

In [33]:
df1['제품'].unique()

array(['gum', 'snack', 'beverage'], dtype=object)

In [34]:
df1['제품'].value_counts()

gum         2
snack       1
beverage    1
Name: 제품, dtype: int64

In [35]:
df1['가격'].describe()    #Describe 함수를 이용한 요약 정리

count       4.000000
mean     1750.000000
std       957.427108
min      1000.000000
25%      1000.000000
50%      1500.000000
75%      2250.000000
max      3000.000000
Name: 가격, dtype: float64

### Indexing

* 특정 변수에 대해 데이터 값을 확인

In [36]:
df1['제품']      #Column이 하나 일 때는 []하나만 써도 되지만

A         gum
B       snack
C    beverage
D         gum
Name: 제품, dtype: object

In [37]:
df1[['제품','가격']]        #Column이 두 개 이상 가져올 때는 대괄호를 두개 붙여줘야 한다 
                            #실무에서는 불필요한 column이 많아, 원하는 column만 추출해 올 필요가 있다

제품    가격
A       gum  1000
B     snack  3000
C  beverage  2000
D       gum  1000

* 범주형 데이터에 대한 연산

In [39]:
table2 = df1[['제품','가격']]
table2

제품    가격
A       gum  1000
B     snack  3000
C  beverage  2000
D       gum  1000

* 대괄호의 개수에 따라 DataFrame / Series 형식이 결정

In [40]:
type(df1['가격'])

pandas.core.series.Series

In [41]:
type(df1[['가격']])

pandas.core.frame.DataFrame

* loc 함수를 이용한 Indexing
    * loc -->해당 index의 row 데이터를 불러온다
    * 특정 위치의 데이터를 Indexing 할 때, 많이 쓰이는 함수이다. (location의 약자)
    * at 함수도 같은 기능을 하지만 , 여러 데이터를 불러올 땐, loc 함수만 작동한다
    
* loc = column명 처럼 명을 기준으로 할 때 많이 쓰이고
* iloc = 명으로 불가한 대신 index기준 즉 숫자를 이용하기 때문에 특정 규칙을 찾아내기 쉽다 

In [42]:
df1.loc['A']    

일자      2019-01-01
가격            1000
구매여부         False
제품             gum
Name: A, dtype: object

In [43]:
df1.loc[['A','D']]

일자    가격   구매여부   제품
A  2019-01-01  1000  False  gum
D  2019-01-06  1000   True  gum

* 범위를 지정하여 Indexing 가능

In [44]:
df1.loc['A':'B']

일자    가격   구매여부     제품
A  2019-01-01  1000  False    gum
B  2019-01-04  3000   True  snack

In [46]:
df1['제품']['B']

'snack'

In [47]:
df1.loc['B','제품']

'snack'

In [48]:
df1.at['B','제품']

'snack'

* loc 함수는 여러 데이터를 불러 올 수 있다

In [49]:
df1.loc[['B','A'],['제품']]

제품
B  snack
A    gum

In [50]:
df1.loc[['A','B'],['제품','가격']]

제품    가격
A    gum  1000
B  snack  3000

In [55]:
ind = ['B','A']
col = ['제품','가격']

df1.loc[ind,col]

제품    가격
B  snack  3000
A    gum  1000

* at함수는 하나의 데이터만 불러 올 수 있다

In [54]:
df1.at[['A','B'],'제품']

TypeError: '['A', 'B']' is an invalid key

* 비교 연산자를 이용한 Indexing

In [57]:
df1['가격']>2000

A    False
B     True
C    False
D    False
Name: 가격, dtype: bool

In [58]:
df1['제품']=='gum'

A     True
B    False
C    False
D     True
Name: 제품, dtype: bool

In [59]:
df1['제품'] != 'gum'

A    False
B     True
C     True
D    False
Name: 제품, dtype: bool

In [60]:
df1[df1['가격'] > 2000]     #dataframe 을 대괄호 밖에 한번 더 언급해주면, 해당 조건을 만족하는 데이터가 출력된다

일자    가격  구매여부     제품
B  2019-01-04  3000  True  snack

In [61]:
df1[df1['제품'] == 'gum']

일자    가격   구매여부   제품
A  2019-01-01  1000  False  gum
D  2019-01-06  1000   True  gum

In [62]:
df1[df1['제품'] != 'gum']

일자    가격  구매여부        제품
B  2019-01-04  3000  True     snack
C  2019-01-06  2000  True  beverage

In [63]:
df1[df1['제품'].isin(['snack','gum'])]    #isin()함수를 이용해, 특정 Column에 있는 여러 데이터를 확인 할 수 있다

일자    가격   구매여부     제품
A  2019-01-01  1000  False    gum
B  2019-01-04  3000   True  snack
D  2019-01-06  1000   True    gum

In [64]:
data = ['gum','snack']
df1[df1['제품'].isin(data)]

일자    가격   구매여부     제품
A  2019-01-01  1000  False    gum
B  2019-01-04  3000   True  snack
D  2019-01-06  1000   True    gum

In [65]:
data = ['gum','snack']
df1[~df1['제품'].isin(data)]     #'~'기호를 이용하면, 해당 조건의 반대가 되는 값을 출력한다

일자    가격  구매여부        제품
C  2019-01-06  2000  True  beverage

### Add / Change / Delete

* 데이터를 새로운 변수에 추가

In [105]:
df1['환불여부']= ['정상','환불','정상','환불']
df1

일자    가격   구매여부        제품 환불여부
A  2019-01-01  1000  False       gum   정상
B  2019-01-04  3000   True     snack   환불
C  2019-01-06  2000   True  beverage   정상
D  2019-01-06  1000   True       gum   환불

In [110]:
condition1 = (df1['구매여부'] == 'True') & (df1['환불여부']=='환불')
df1.loc[condition1, '판매여부'] = False
df1.loc[~condition1, '판매여부'] = True                #loc함수를 이용해서 새로운 DataFrame을 만들어줌 
df1

일자    가격   구매여부        제품 환불여부   판매여부
A  2019-01-01  1000  False       gum   정상   True
B  2019-01-04  3000   True     snack   환불  False
C  2019-01-06  2000   True  beverage   정상   True
D  2019-01-06  1000   True       gum   환불  False

* 데이터를 삭제
* * drop() ----> 그냥 안보이게만 해주는 것 사실은 있음
* * drop('?',axis=0,1, inplace = True)   ---> 아예 삭제 해주는 것

In [111]:
df1.drop('B',axis = 0)

일자    가격   구매여부        제품 환불여부   판매여부
A  2019-01-01  1000  False       gum   정상   True
C  2019-01-06  2000   True  beverage   정상   True
D  2019-01-06  1000   True       gum   환불  False

In [112]:
df1.drop('구매여부',axis = 1)

일자    가격        제품 환불여부   판매여부
A  2019-01-01  1000       gum   정상   True
B  2019-01-04  3000     snack   환불  False
C  2019-01-06  2000  beverage   정상   True
D  2019-01-06  1000       gum   환불  False

* 문자열 Replace 함수를 이용한 특정 값 변경

In [114]:
df1['판매여부'].replace(True,1)

A    1.0
B    0.0
C    1.0
D    0.0
Name: 판매여부, dtype: float64

In [116]:
df1['판매여부(replace)'] = df1['판매여부'].replace(True,1)
df1

일자    가격   구매여부        제품 환불여부   판매여부  판매여부(replace)
A  2019-01-01  1000  False       gum   정상   True            1.0
B  2019-01-04  3000   True     snack   환불  False            0.0
C  2019-01-06  2000   True  beverage   정상   True            1.0
D  2019-01-06  1000   True       gum   환불  False            0.0

In [121]:
df1['제품'].replace('snack','스낵')

A         gum
B          스낵
C    beverage
D         gum
Name: 제품, dtype: object

* 문자열 Replace 함수를 이어 사용하여 특정 값 변경

In [122]:
df1['제품'].replace('snack','스낵').replace('gum','껌').replace('beverage','음료')

A     껌
B    스낵
C    음료
D     껌
Name: 제품, dtype: object

In [123]:
df1['제품(replace)'] = df1['제품'].replace('snack','스낵').replace('gum','껌').replace('beverage','음료')
df1

일자    가격   구매여부        제품 환불여부   판매여부  판매여부(replace) 제품(replace)
A  2019-01-01  1000  False       gum   정상   True            1.0           껌
B  2019-01-04  3000   True     snack   환불  False            0.0          스낵
C  2019-01-06  2000   True  beverage   정상   True            1.0          음료
D  2019-01-06  1000   True       gum   환불  False            0.0           껌